## PyTorch Fundamental

In [ ]:
import torch
torch.__version__

'2.1.0+cu121'

In [ ]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

## Introduction to Tensor

### Creating tensors


In [ ]:
##scalar
#a single number with	dimention 0
scalar = torch.tensor(7)
scalar

tensor(7)

In [ ]:
scalar.ndim

0

In [ ]:
#Get tensor back as Python int
scalar.item()

7

In [ ]:
##vector
#a number with direction with dimention	1
vector = torch.tensor([7,7])
vector

tensor([7, 7])

In [ ]:
vector.ndim

1

In [ ]:
vector.shape

torch.Size([2])

In [ ]:
##MATRIX
#a 2-dimensional array of numbers with dimention	2
MATRIX = torch.tensor([[7,8],
                       [9,10]])
MATRIX

tensor([[ 7,  8],
        [ 9, 10]])

In [ ]:
MATRIX.ndim

2

In [ ]:
MATRIX[1]

tensor([ 9, 10])

In [ ]:
MATRIX.shape


torch.Size([2, 2])

In [ ]:
##TENSOR
#an n-dimensional array of numbers with a dimention that can be any number
TENSOR = torch.tensor([[[1,2,3],
                        [3,6,9],
                        [2,4,5]]])
TENSOR

tensor([[[1, 2, 3],
         [3, 6, 9],
         [2, 4, 5]]])

In [ ]:
TENSOR.ndim

3

In [ ]:
TENSOR.shape

torch.Size([1, 3, 3])

In [ ]:
TENSOR[0]

tensor([[1, 2, 3],
        [3, 6, 9],
        [2, 4, 5]])

In [ ]:
TENSOR[0][0]

tensor([1, 2, 3])

###Random tensors

 A machine learning model often starts out with large random tensors of numbers and adjusts these random numbers as it works through data to better represent it.

 *Start with random numbers -> look at data -> update random numbers -> look at data -> update random numbers*

In [ ]:
#Create a random tensor of size(3, 4)
random_tensor = torch.rand(3,4)
random_tensor

tensor([[0.3947, 0.0563, 0.6473, 0.1901],
        [0.3986, 0.2239, 0.4319, 0.8779],
        [0.9412, 0.0528, 0.3106, 0.5186]])

In [ ]:
random_tensor.ndim

2

In [ ]:
#Create a random tensor with similar shape to an image tensor
random_image_size_tensor = torch.rand(size=(3, 224, 224)) #height, width, color channel (R, G, B)
random_image_size_tensor.shape, random_image_size_tensor.ndim

(torch.Size([3, 224, 224]), 3)

### Zeros and ones

In [ ]:
#Create a tensor of all zeros
zeros = torch.zeros(3,4)
zeros

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [ ]:
#Create a tensor of all ones
ones = torch.ones(size=(3,4))
ones

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [ ]:
ones.dtype #what type of data type is

torch.float32

### Creating a range of tensors and tensors-like

In [ ]:
#Use torch.arange()
one_to_ten = torch.arange(1,11)
one_to_ten

tensor([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [ ]:
another = torch.arange(start = 0, end = 1000, step = 25)
another

tensor([  0,  25,  50,  75, 100, 125, 150, 175, 200, 225, 250, 275, 300, 325,
        350, 375, 400, 425, 450, 475, 500, 525, 550, 575, 600, 625, 650, 675,
        700, 725, 750, 775, 800, 825, 850, 875, 900, 925, 950, 975])

In [ ]:
#Creating tensors like
ten_zeros = torch.zeros_like(input = one_to_ten)
ten_zeros

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [ ]:
ten_zeros_another = torch.zeros_like(input = torch.arange(1,11))
ten_zeros_another

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

###Tensor datatypes

In [ ]:
float_32_tensor = torch.tensor([3.0, 6.0, 9.0],
                               dtype=None, #defaults to None, which is torch.float32 or whatever datatype is passed
                               device=None, # defaults to None, which uses the default tensor type
                               requires_grad=False) # if True, operations performed on the tensor are recorded
float_32_tensor

tensor([3., 6., 9.])

In [ ]:
float_32_tensor.dtype

torch.float32

In [ ]:
float_16_tensor = float_32_tensor.type(torch.float16)

float_16_tensor.dtype

torch.float16

In [ ]:
float_16_tensor * float_32_tensor

tensor([ 9., 36., 81.])

In [ ]:
int_32_tensor = torch.tensor([3,6,9], dtype = torch.int32)
int_32_tensor

tensor([3, 6, 9], dtype=torch.int32)

In [ ]:
float_32_tensor * int_32_tensor

tensor([ 9., 36., 81.])

###Getting attributes from tensor

the most common attributes you'll want to find out about tensors are:

*   shape - what shape is the tensor? (some operations require specific shape rules)
*   dtype - what datatype are the elements within the tensor stored in?
*   device - what device is the tensor stored on? (usually GPU or CPU)



In [ ]:
# Create a tensor
some_tensor = torch.rand(3, 4)
some_tensor

tensor([[0.5266, 0.3612, 0.2017, 0.8446],
        [0.3169, 0.1684, 0.4135, 0.3308],
        [0.7830, 0.4927, 0.4560, 0.8441]])

In [ ]:
# Find out details about it
print(some_tensor)
print(f"Shape of tensor: {some_tensor.shape}")
print(f"Datatype of tensor: {some_tensor.dtype}")
print(f"Device tensor is stored on: {some_tensor.device}") # will default to CPU

tensor([[0.5266, 0.3612, 0.2017, 0.8446],
        [0.3169, 0.1684, 0.4135, 0.3308],
        [0.7830, 0.4927, 0.4560, 0.8441]])
Shape of tensor: torch.Size([3, 4])
Datatype of tensor: torch.float32
Device tensor is stored on: cpu
