<a href="https://colab.research.google.com/github/camipeso/pytorch-youtube-course/blob/main/Chapter_0.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## PyTorch Fundamental

In [2]:
import torch
torch.__version__

'2.1.0+cu121'

In [3]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

## Introduction to Tensor

### Creating tensors


In [4]:
##scalar
#a single number with	dimention 0
scalar = torch.tensor(7)
scalar

tensor(7)

In [5]:
scalar.ndim

0

In [6]:
#Get tensor back as Python int
scalar.item()

7

In [7]:
##vector
#a number with direction with dimention	1
vector = torch.tensor([7,7])
vector

tensor([7, 7])

In [8]:
vector.ndim

1

In [9]:
vector.shape

torch.Size([2])

In [10]:
##MATRIX
#a 2-dimensional array of numbers with dimention	2
MATRIX = torch.tensor([[7,8],
                       [9,10]])
MATRIX

tensor([[ 7,  8],
        [ 9, 10]])

In [11]:
MATRIX.ndim

2

In [12]:
MATRIX[1]

tensor([ 9, 10])

In [13]:
MATRIX.shape


torch.Size([2, 2])

In [14]:
##TENSOR
#an n-dimensional array of numbers with a dimention that can be any number
TENSOR = torch.tensor([[[1,2,3],
                        [3,6,9],
                        [2,4,5]]])
TENSOR

tensor([[[1, 2, 3],
         [3, 6, 9],
         [2, 4, 5]]])

In [15]:
TENSOR.ndim

3

In [16]:
TENSOR.shape

torch.Size([1, 3, 3])

In [17]:
TENSOR[0]

tensor([[1, 2, 3],
        [3, 6, 9],
        [2, 4, 5]])

In [18]:
TENSOR[0][0]

tensor([1, 2, 3])

###Random tensors

 A machine learning model often starts out with large random tensors of numbers and adjusts these random numbers as it works through data to better represent it.

 *Start with random numbers -> look at data -> update random numbers -> look at data -> update random numbers*

In [19]:
#Create a random tensor of size(3, 4)
random_tensor = torch.rand(3,4)
random_tensor

tensor([[0.6152, 0.6090, 0.5784, 0.8183],
        [0.2165, 0.8804, 0.2721, 0.2484],
        [0.6413, 0.7913, 0.7059, 0.0931]])

In [20]:
random_tensor.ndim

2

In [21]:
#Create a random tensor with similar shape to an image tensor
random_image_size_tensor = torch.rand(size=(3, 224, 224)) #height, width, color channel (R, G, B)
random_image_size_tensor.shape, random_image_size_tensor.ndim

(torch.Size([3, 224, 224]), 3)

### Zeros and ones

In [22]:
#Create a tensor of all zeros
zeros = torch.zeros(3,4)
zeros

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [23]:
#Create a tensor of all ones
ones = torch.ones(size=(3,4))
ones

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [24]:
ones.dtype #what type of data type is

torch.float32

### Creating a range of tensors and tensors-like

In [25]:
#Use torch.arange()
one_to_ten = torch.arange(1,11)
one_to_ten

tensor([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [26]:
another = torch.arange(start = 0, end = 1000, step = 25)
another

tensor([  0,  25,  50,  75, 100, 125, 150, 175, 200, 225, 250, 275, 300, 325,
        350, 375, 400, 425, 450, 475, 500, 525, 550, 575, 600, 625, 650, 675,
        700, 725, 750, 775, 800, 825, 850, 875, 900, 925, 950, 975])

In [27]:
#Creating tensors like
ten_zeros = torch.zeros_like(input = one_to_ten)
ten_zeros

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [28]:
ten_zeros_another = torch.zeros_like(input = torch.arange(1,11))
ten_zeros_another

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

###Tensor datatypes

In [29]:
float_32_tensor = torch.tensor([3.0, 6.0, 9.0],
                               dtype=None, #defaults to None, which is torch.float32 or whatever datatype is passed
                               device=None, # defaults to None, which uses the default tensor type
                               requires_grad=False) # if True, operations performed on the tensor are recorded
float_32_tensor

tensor([3., 6., 9.])

In [30]:
float_32_tensor.dtype

torch.float32

In [31]:
float_16_tensor = float_32_tensor.type(torch.float16)

float_16_tensor.dtype

torch.float16

In [32]:
float_16_tensor * float_32_tensor

tensor([ 9., 36., 81.])

In [33]:
int_32_tensor = torch.tensor([3,6,9], dtype = torch.int32)
int_32_tensor

tensor([3, 6, 9], dtype=torch.int32)

In [34]:
float_32_tensor * int_32_tensor

tensor([ 9., 36., 81.])

###Getting attributes from tensor

the most common attributes you'll want to find out about tensors are:

*   shape - what shape is the tensor? (some operations require specific shape rules)
*   dtype - what datatype are the elements within the tensor stored in?
*   device - what device is the tensor stored on? (usually GPU or CPU)



In [35]:
# Create a tensor
some_tensor = torch.rand(3, 4)
some_tensor

tensor([[0.4965, 0.7719, 0.6933, 0.0377],
        [0.2334, 0.7339, 0.6325, 0.4822],
        [0.5428, 0.9490, 0.6437, 0.3986]])

In [36]:
# Find out details about it
print(some_tensor)
print(f"Shape of tensor: {some_tensor.shape}")
print(f"Datatype of tensor: {some_tensor.dtype}")
print(f"Device tensor is stored on: {some_tensor.device}") # will default to CPU

tensor([[0.4965, 0.7719, 0.6933, 0.0377],
        [0.2334, 0.7339, 0.6325, 0.4822],
        [0.5428, 0.9490, 0.6437, 0.3986]])
Shape of tensor: torch.Size([3, 4])
Datatype of tensor: torch.float32
Device tensor is stored on: cpu


###Manipulatting Tensors (tensor operations)

Tensor operations include:
* Addition
* Subtraction
* Multiplication (element-wise)
* Division
* Matrix multiplication

In [38]:
#Create a tensor and add 10 to it
tensor = torch.tensor([1,2,3])
tensor + 10

tensor([11, 12, 13])

In [40]:
#Multiply tensor by 10
tensor * 10

tensor([10, 20, 30])

In [41]:
#Substract 10
tensor -10

tensor([-9, -8, -7])

In [42]:
#Try out PyTorch in-build functions
torch.mul(tensor, 10)

tensor([10, 20, 30])

In [43]:
torch.add(tensor, 10)

tensor([11, 12, 13])

### Matrix multiplications

There are two main ways of performing multiplications in neural networks and deep learning:
1. Element-wise multiplication
2. Matrix multiplication (dot product)

In [44]:
#Element-wise multiplication
print(tensor, '*', tensor)
print(f"Equals: {tensor * tensor}")

tensor([1, 2, 3]) * tensor([1, 2, 3])
Equals: tensor([1, 4, 9])


In [45]:
#Matrix multiplication
torch.matmul(tensor,tensor)

tensor(14)

### One of the most common errors in deep learning (shape errors): Shape erros

In [47]:
#Shape for matrix multiplication
tensor_A = torch.tensor([[1, 2],
                         [3, 4],
                         [5, 6]], dtype=torch.float32)

tensor_B = torch.tensor([[7, 10],
                         [8, 11],
                         [9, 12]], dtype=torch.float32)

torch.matmul(tensor_A, tensor_B) # (this will error)

RuntimeError: mat1 and mat2 shapes cannot be multiplied (3x2 and 3x2)

In [48]:
# View tensor_A and tensor_B.T
print(tensor_A)
print(tensor_B.T)

tensor([[1., 2.],
        [3., 4.],
        [5., 6.]])
tensor([[ 7.,  8.,  9.],
        [10., 11., 12.]])


In [49]:
# The operation works when tensor_B is transposed
print(f"Original shapes: tensor_A = {tensor_A.shape}, tensor_B = {tensor_B.shape}\n")
print(f"New shapes: tensor_A = {tensor_A.shape} (same as above), tensor_B.T = {tensor_B.T.shape}\n")
print(f"Multiplying: {tensor_A.shape} * {tensor_B.T.shape} <- inner dimensions match\n")
print("Output:\n")
output = torch.matmul(tensor_A, tensor_B.T)
print(output)
print(f"\nOutput shape: {output.shape}")

Original shapes: tensor_A = torch.Size([3, 2]), tensor_B = torch.Size([3, 2])

New shapes: tensor_A = torch.Size([3, 2]) (same as above), tensor_B.T = torch.Size([2, 3])

Multiplying: torch.Size([3, 2]) * torch.Size([2, 3]) <- inner dimensions match

Output:

tensor([[ 27.,  30.,  33.],
        [ 61.,  68.,  75.],
        [ 95., 106., 117.]])

Output shape: torch.Size([3, 3])


### Finding the min, max, mean, sum, ect (tensor aggregation)

In [55]:
#create a tensor
x = torch.arange(0,100,10)
x, x.dtype

(tensor([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90]), torch.int64)

In [52]:
#Find the max
torch.min(x), x.min()

(tensor(0), tensor(0))

In [53]:
#Find the max
torch.max(x), x.max()

(tensor(90), tensor(90))

In [57]:
#Find the mean
torch.mean(x.type(torch.float32)), x.type(torch.float32).mean()

(tensor(45.), tensor(45.))

In [58]:
#Find the sum
torch.sum(x), x.sum()

(tensor(450), tensor(450))