<a href="https://colab.research.google.com/github/camipeso/pytorch-youtube-course/blob/main/Chapter_0.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## PyTorch Fundamental

In [1]:
import torch
torch.__version__

'2.1.0+cu121'

In [2]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

## Introduction to Tensor

### Creating tensors


In [3]:
##scalar
#a single number with	dimention 0
scalar = torch.tensor(7)
scalar

tensor(7)

In [4]:
scalar.ndim

0

In [5]:
#Get tensor back as Python int
scalar.item()

7

In [6]:
##vector
#a number with direction with dimention	1
vector = torch.tensor([7,7])
vector

tensor([7, 7])

In [7]:
vector.ndim

1

In [8]:
vector.shape

torch.Size([2])

In [9]:
##MATRIX
#a 2-dimensional array of numbers with dimention	2
MATRIX = torch.tensor([[7,8],
                       [9,10]])
MATRIX

tensor([[ 7,  8],
        [ 9, 10]])

In [10]:
MATRIX.ndim

2

In [11]:
MATRIX[1]

tensor([ 9, 10])

In [12]:
MATRIX.shape


torch.Size([2, 2])

In [13]:
##TENSOR
#an n-dimensional array of numbers with a dimention that can be any number
TENSOR = torch.tensor([[[1,2,3],
                        [3,6,9],
                        [2,4,5]]])
TENSOR

tensor([[[1, 2, 3],
         [3, 6, 9],
         [2, 4, 5]]])

In [14]:
TENSOR.ndim

3

In [15]:
TENSOR.shape

torch.Size([1, 3, 3])

In [16]:
TENSOR[0]

tensor([[1, 2, 3],
        [3, 6, 9],
        [2, 4, 5]])

In [17]:
TENSOR[0][0]

tensor([1, 2, 3])

###Random tensors

 A machine learning model often starts out with large random tensors of numbers and adjusts these random numbers as it works through data to better represent it.

 *Start with random numbers -> look at data -> update random numbers -> look at data -> update random numbers*

In [18]:
#Create a random tensor of size(3, 4)
random_tensor = torch.rand(3,4)
random_tensor

tensor([[0.6679, 0.9597, 0.6533, 0.0207],
        [0.5959, 0.1444, 0.1243, 0.6921],
        [0.6694, 0.7137, 0.0580, 0.5072]])

In [19]:
random_tensor.ndim

2

In [20]:
#Create a random tensor with similar shape to an image tensor
random_image_size_tensor = torch.rand(size=(3, 224, 224)) #height, width, color channel (R, G, B)
random_image_size_tensor.shape, random_image_size_tensor.ndim

(torch.Size([3, 224, 224]), 3)

### Zeros and ones

In [21]:
#Create a tensor of all zeros
zeros = torch.zeros(3,4)
zeros

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [22]:
#Create a tensor of all ones
ones = torch.ones(size=(3,4))
ones

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [23]:
ones.dtype #what type of data type is

torch.float32

### Creating a range of tensors and tensors-like

In [24]:
#Use torch.arange()
one_to_ten = torch.arange(1,11)
one_to_ten

tensor([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [25]:
another = torch.arange(start = 0, end = 1000, step = 25)
another

tensor([  0,  25,  50,  75, 100, 125, 150, 175, 200, 225, 250, 275, 300, 325,
        350, 375, 400, 425, 450, 475, 500, 525, 550, 575, 600, 625, 650, 675,
        700, 725, 750, 775, 800, 825, 850, 875, 900, 925, 950, 975])

In [26]:
#Creating tensors like
ten_zeros = torch.zeros_like(input = one_to_ten)
ten_zeros

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [27]:
ten_zeros_another = torch.zeros_like(input = torch.arange(1,11))
ten_zeros_another

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

###Tensor datatypes

In [28]:
float_32_tensor = torch.tensor([3.0, 6.0, 9.0],
                               dtype=None, #defaults to None, which is torch.float32 or whatever datatype is passed
                               device=None, # defaults to None, which uses the default tensor type
                               requires_grad=False) # if True, operations performed on the tensor are recorded
float_32_tensor

tensor([3., 6., 9.])

In [29]:
float_32_tensor.dtype

torch.float32

In [30]:
float_16_tensor = float_32_tensor.type(torch.float16)

float_16_tensor.dtype

torch.float16

In [31]:
float_16_tensor * float_32_tensor

tensor([ 9., 36., 81.])

In [32]:
int_32_tensor = torch.tensor([3,6,9], dtype = torch.int32)
int_32_tensor

tensor([3, 6, 9], dtype=torch.int32)

In [33]:
float_32_tensor * int_32_tensor

tensor([ 9., 36., 81.])

###Getting attributes from tensor

the most common attributes you'll want to find out about tensors are:

*   shape - what shape is the tensor? (some operations require specific shape rules)
*   dtype - what datatype are the elements within the tensor stored in?
*   device - what device is the tensor stored on? (usually GPU or CPU)



In [34]:
# Create a tensor
some_tensor = torch.rand(3, 4)
some_tensor

tensor([[0.9312, 0.3421, 0.6948, 0.0238],
        [0.9462, 0.9038, 0.9730, 0.6190],
        [0.3829, 0.0139, 0.9741, 0.3016]])

In [35]:
# Find out details about it
print(some_tensor)
print(f"Shape of tensor: {some_tensor.shape}")
print(f"Datatype of tensor: {some_tensor.dtype}")
print(f"Device tensor is stored on: {some_tensor.device}") # will default to CPU

tensor([[0.9312, 0.3421, 0.6948, 0.0238],
        [0.9462, 0.9038, 0.9730, 0.6190],
        [0.3829, 0.0139, 0.9741, 0.3016]])
Shape of tensor: torch.Size([3, 4])
Datatype of tensor: torch.float32
Device tensor is stored on: cpu


###Manipulatting Tensors (tensor operations)

Tensor operations include:
* Addition
* Subtraction
* Multiplication (element-wise)
* Division
* Matrix multiplication

In [36]:
#Create a tensor and add 10 to it
tensor = torch.tensor([1,2,3])
tensor + 10

tensor([11, 12, 13])

In [37]:
#Multiply tensor by 10
tensor * 10

tensor([10, 20, 30])

In [38]:
#Substract 10
tensor -10

tensor([-9, -8, -7])

In [39]:
#Try out PyTorch in-build functions
torch.mul(tensor, 10)

tensor([10, 20, 30])

In [40]:
torch.add(tensor, 10)

tensor([11, 12, 13])

### Matrix multiplications

There are two main ways of performing multiplications in neural networks and deep learning:
1. Element-wise multiplication
2. Matrix multiplication (dot product)

In [41]:
#Element-wise multiplication
print(tensor, '*', tensor)
print(f"Equals: {tensor * tensor}")

tensor([1, 2, 3]) * tensor([1, 2, 3])
Equals: tensor([1, 4, 9])


In [42]:
#Matrix multiplication
torch.matmul(tensor,tensor)

tensor(14)

### One of the most common errors in deep learning (shape errors): Shape erros

In [43]:
#Shape for matrix multiplication
tensor_A = torch.tensor([[1, 2],
                         [3, 4],
                         [5, 6]], dtype=torch.float32)

tensor_B = torch.tensor([[7, 10],
                         [8, 11],
                         [9, 12]], dtype=torch.float32)

torch.matmul(tensor_A, tensor_B) # (this will error)

RuntimeError: mat1 and mat2 shapes cannot be multiplied (3x2 and 3x2)

In [44]:
# View tensor_A and tensor_B.T
print(tensor_A)
print(tensor_B.T)

tensor([[1., 2.],
        [3., 4.],
        [5., 6.]])
tensor([[ 7.,  8.,  9.],
        [10., 11., 12.]])


In [45]:
# The operation works when tensor_B is transposed
print(f"Original shapes: tensor_A = {tensor_A.shape}, tensor_B = {tensor_B.shape}\n")
print(f"New shapes: tensor_A = {tensor_A.shape} (same as above), tensor_B.T = {tensor_B.T.shape}\n")
print(f"Multiplying: {tensor_A.shape} * {tensor_B.T.shape} <- inner dimensions match\n")
print("Output:\n")
output = torch.matmul(tensor_A, tensor_B.T)
print(output)
print(f"\nOutput shape: {output.shape}")

Original shapes: tensor_A = torch.Size([3, 2]), tensor_B = torch.Size([3, 2])

New shapes: tensor_A = torch.Size([3, 2]) (same as above), tensor_B.T = torch.Size([2, 3])

Multiplying: torch.Size([3, 2]) * torch.Size([2, 3]) <- inner dimensions match

Output:

tensor([[ 27.,  30.,  33.],
        [ 61.,  68.,  75.],
        [ 95., 106., 117.]])

Output shape: torch.Size([3, 3])


### Finding the min, max, mean, sum, ect (tensor aggregation)

In [46]:
#create a tensor
x = torch.arange(0,100,10)
x, x.dtype

(tensor([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90]), torch.int64)

In [47]:
#Find the max
torch.min(x), x.min()

(tensor(0), tensor(0))

In [48]:
#Find the max
torch.max(x), x.max()

(tensor(90), tensor(90))

In [ ]:
#Find the mean
torch.mean(x.type(torch.float32)), x.type(torch.float32).mean()

In [50]:
#Find the sum
torch.sum(x), x.sum()

(tensor(450), tensor(450))

###Finding the positional min and max

In [51]:
#Find the positioin in tensor that has the minimum value with argmin
# -> returns index position of target tensor where the minimum value occurs
x.argmin()

tensor(0)

In [52]:
#Find the positioin in tensor that has the maximum value with argmax
x.argmax()

tensor(9)

##Reshaping, stacking, squeezing and unsqueezing tensors

* Reshaping - reshapes an input tensor to a defined shape
* View - return a view of an input tensor of certain chape but keep the same memory as the original  tensor
* Stacking - combine multiple tnesor on top of each other (vstack) or side by side (hstack)
* Squeese - removes all `1` dimensions from a tensor
* Unsqueeze - add a `1` dimention to a target tensor
* Permute - return a view of the input with dimensions permuted (swapped) in a certain way


In [54]:
#Create a tensor
import torch
x = torch.arange(1.,10.)
x, x.shape

(tensor([1., 2., 3., 4., 5., 6., 7., 8., 9.]), torch.Size([9]))

In [64]:
#Add an extra dimention
x_reshaped = x.reshape(1,9)
x_reshaped, x_reshaped.shape

(tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.]]), torch.Size([1, 9]))

In [57]:
x_reshaped = x.reshape(9,1)
x_reshaped, x_reshaped.shape

(tensor([[1.],
         [2.],
         [3.],
         [4.],
         [5.],
         [6.],
         [7.],
         [8.],
         [9.]]),
 torch.Size([9, 1]))

In [58]:
x_reshaped = x.reshape(3,3)
x_reshaped, x_reshaped.shape

(tensor([[1., 2., 3.],
         [4., 5., 6.],
         [7., 8., 9.]]),
 torch.Size([3, 3]))

In [59]:
#Change the view
z = x.view(1,9)
z, z.shape

(tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.]]), torch.Size([1, 9]))

In [60]:
# Changing z changes x
z[:, 0] = 5
z, x

(tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.]]),
 tensor([5., 2., 3., 4., 5., 6., 7., 8., 9.]))

In [61]:
#Stack tensor on top of each other
x_stacked = torch.stack([x, x, x, x], dim =0)
x_stacked

tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.],
        [5., 2., 3., 4., 5., 6., 7., 8., 9.],
        [5., 2., 3., 4., 5., 6., 7., 8., 9.],
        [5., 2., 3., 4., 5., 6., 7., 8., 9.]])

In [62]:
x_stacked = torch.stack([x, x, x, x], dim =1)
x_stacked

tensor([[5., 5., 5., 5.],
        [2., 2., 2., 2.],
        [3., 3., 3., 3.],
        [4., 4., 4., 4.],
        [5., 5., 5., 5.],
        [6., 6., 6., 6.],
        [7., 7., 7., 7.],
        [8., 8., 8., 8.],
        [9., 9., 9., 9.]])

In [65]:
#torch.squeeze() - removes all single dimentions from a target tensor
x_reshaped = x.reshape(1,9)
x_reshaped, x_reshaped.shape

(tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.]]), torch.Size([1, 9]))

In [67]:
x_reshaped.squeeze(), x_reshaped.squeeze().shape

(tensor([5., 2., 3., 4., 5., 6., 7., 8., 9.]), torch.Size([9]))

In [68]:
print(f"Previous tensor: {x_reshaped}")
print(f"Previous shape: {x_reshaped.shape}")

# Remove extra dimension from x_reshaped
x_squeezed = x_reshaped.squeeze()
print(f"\nNew tensor: {x_squeezed}")
print(f"New shape: {x_squeezed.shape}")

Previous tensor: tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.]])
Previous shape: torch.Size([1, 9])

New tensor: tensor([5., 2., 3., 4., 5., 6., 7., 8., 9.])
New shape: torch.Size([9])


In [69]:
#torch.unsqueeze() - adds a single dimention to a target tensor at a specific dimention
print(f"Previous tensor: {x_squeezed}")
print(f"Previous shape: {x_squeezed.shape}")

## Add an extra dimension with unsqueeze
x_unsqueezed = x_squeezed.unsqueeze(dim=0)
print(f"\nNew tensor: {x_unsqueezed}")
print(f"New shape: {x_unsqueezed.shape}")

Previous tensor: tensor([5., 2., 3., 4., 5., 6., 7., 8., 9.])
Previous shape: torch.Size([9])

New tensor: tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.]])
New shape: torch.Size([1, 9])


In [70]:
# torch.permute() - rearrenges the dimentions of a target tensor ina  specified order
# Create tensor with specific shape
x_original = torch.rand(size=(224, 224, 3)) #[height, width, colour_channels]

# Permute the original tensor to rearrange the axis order
x_permuted = x_original.permute(2, 0, 1) # shifts axis 0->1, 1->2, 2->0

print(f"Previous shape: {x_original.shape}")
print(f"New shape: {x_permuted.shape}") #[colour_channels, height, width]

Previous shape: torch.Size([224, 224, 3])
New shape: torch.Size([3, 224, 224])


### Indexing - selecting data from tensors

Indexing PyTorch is similar to indexing with NumPy

In [71]:
#Create a tensor
import torch
x = torch.arange(1,10).reshape(1,3,3)
x, x.shape

(tensor([[[1, 2, 3],
          [4, 5, 6],
          [7, 8, 9]]]),
 torch.Size([1, 3, 3]))

In [72]:
#Indexing
x[0]

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [76]:
x[0][0]

tensor([1, 2, 3])

In [77]:
x[0, 0] #same resuls as the previus one

tensor([1, 2, 3])

In [78]:
x[0][0][0]

tensor(1)

In [79]:
# the : can be use to select all of a target dimention
x[:, 0]

tensor([[1, 2, 3]])

In [80]:
# Get all values of 0th & 1st dimensions but only index 1 of 2nd dimension
x[:, :, 1]

tensor([[2, 5, 8]])

PyTorch tensors & NumPy
Since NumPy is a popular Python numerical computing library, PyTorch has functionality to interact with it nicely.

The two main methods you'll want to use for NumPy to PyTorch (and back again) are:

* torch.from_numpy(ndarray) - NumPy array -> PyTorch tensor.
* torch.Tensor.numpy() - PyTorch tensor -> NumPy array

In [82]:
# NumPy array to tensor
import torch
import numpy as np
array = np.arange(1.0, 8.0)
tensor = torch.from_numpy(array) #warning: when converting from numpy -> pytorch reflects numpy's default datatype of float64 unless specified otherwise
array, tensor

(array([1., 2., 3., 4., 5., 6., 7.]),
 tensor([1., 2., 3., 4., 5., 6., 7.], dtype=torch.float64))

In [83]:
#Change the value to array, what will happend to tensor?
array = array + 1
array, tensor

(array([2., 3., 4., 5., 6., 7., 8.]),
 tensor([1., 2., 3., 4., 5., 6., 7.], dtype=torch.float64))

In [85]:
#Tensor to Numpy array
tensor = torch.ones(7)
numpy_tensor = tensor.numpy()
tensor, numpy_tensor

(tensor([1., 1., 1., 1., 1., 1., 1.]),
 array([1., 1., 1., 1., 1., 1., 1.], dtype=float32))

In [86]:
#Change the tensor, what happens to array?
tensor = tensor + 1
tensor, numpy_tensor

(tensor([2., 2., 2., 2., 2., 2., 2.]),
 array([1., 1., 1., 1., 1., 1., 1.], dtype=float32))

###Reproducibility (trying to take the random out of random)

In Short how a neural network leanrs:

`start with random numbers -> tensor operations -> try to make better (again and again and again)`

To reduce the randomness in neural networks and PyTorch comes the convept of a **random seed**.


In [87]:
import torch

#Create two random tensors
random_tensor_A = torch.rand(3, 4)
random_tensor_B = torch.rand(3, 4)

print(f"Tensor A:\n{random_tensor_A}\n")
print(f"Tensor B:\n{random_tensor_B}\n")
print(f"Does Tensor A equal Tensor B? (anywhere)")
random_tensor_A == random_tensor_B

Tensor A:
tensor([[0.2820, 0.4926, 0.4211, 0.9475],
        [0.2340, 0.4038, 0.5597, 0.7223],
        [0.9476, 0.7101, 0.3636, 0.4084]])

Tensor B:
tensor([[0.0557, 0.9681, 0.2606, 0.2534],
        [0.9602, 0.3169, 0.8876, 0.6755],
        [0.9331, 0.1380, 0.0514, 0.7343]])

Does Tensor A equal Tensor B? (anywhere)


tensor([[False, False, False, False],
        [False, False, False, False],
        [False, False, False, False]])

In [89]:
#Let's make some random but reproducible tensors

#Set the random seed
RANDOM_SEED = 42

torch.manual_seed(RANDOM_SEED)
random_tensor_C = torch.rand(3, 4)

torch.manual_seed(RANDOM_SEED)
random_tensor_D = torch.rand(3, 4)

print(f"Tensor C:\n{random_tensor_C}\n")
print(f"Tensor D:\n{random_tensor_D}\n")
print(f"Does Tensor D equal Tensor D? (anywhere)")
random_tensor_C == random_tensor_D

Tensor C:
tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])

Tensor D:
tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])

Does Tensor D equal Tensor D? (anywhere)


tensor([[True, True, True, True],
        [True, True, True, True],
        [True, True, True, True]])